name: 'entelechy_ui'
version: 0.0.1
description: Minimal UI for prototyping liveness in Fletch

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  browser: '>=0.10.0 <0.11.0'
  codemirror: '>=0.2.8 <0.3.0'
  http: '>=0.11.1 <0.12.0'
  logging: '^0.11.2'
